// <auto-generated />
using ECommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronics",
                            Description = "Electronic devices and gadgets"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Clothing",
                            Description = "Men and women apparel"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Accessories",
                            Description = "Bags, watches and more"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Shoes",
                            Description = "Footwear for all occasions"
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Premium noise cancelling headphones",
                            ImageUrl = "https://example.com/headphones.jpg",
                            Name = "Wireless Headphones",
                            Price = 199.99m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Feature packed smartwatch",
                            ImageUrl = "https://example.com/smartwatch.jpg",
                            Name = "Smart Watch Pro",
                            Price = 299.99m,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Description = "Comfortable everyday t-shirt",
                            ImageUrl = "https://example.com/tshirt.jpg",
                            Name = "Cotton T-Shirt",
                            Price = 29.99m,
                            Stock = 100
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Classic slim fit jeans",
                            ImageUrl = "https://example.com/jeans.jpg",
                            Name = "Denim Jeans",
                            Price = 69.99m,
                            Stock = 75
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Warm jacket for cold weather",
                            ImageUrl = "https://example.com/jacket.jpg",
                            Name = "Winter Jacket",
                            Price = 149.99m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Description = "Classic leather strap watch",
                            ImageUrl = "https://example.com/watch.jpg",
                            Name = "Leather Watch",
                            Price = 149.99m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "UV protected stylish sunglasses",
                            ImageUrl = "https://example.com/sunglasses.jpg",
                            Name = "Designer Sunglasses",
                            Price = 179.99m,
                            Stock = 60
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            Description = "Lightweight shoes for running",
                            ImageUrl = "https://example.com/shoes.jpg",
                            Name = "Running Shoes",
                            Price = 89.99m,
                            Stock = 80
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.Product", b =>
                {
                    b.HasOne("ECommerceApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerceApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
